
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:delegated
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - PYTHONUNBUFFERED=1
    depends_on:
      ollama-init:
        condition: service_completed_successfully
    entrypoint: >
      sh -c "
        echo 'Waiting for Ollama...';
        until curl -s ollama:11434; do
          sleep 5;
        done;
        exec /app/venv/bin/python server.py
      "
    networks:
      - app_network
