version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - ollama
    environment:
      - BACKEND_URL=http://backend:8000
      - OLLAMA_URL=http://localhost:11434  # Updated for browser access

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434  # Correct within Docker network

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_CPU_ONLY=true
      - OLLAMA_HOST=0.0.0.0  # Ensure binding to all interfaces

  # model-puller:
  #   image: curlimages/curl
  #   depends_on:
  #     - ollama
  #   command: >
  #     sh -c "sleep 15 &&  # Increased sleep to ensure Ollama is up
  #            curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"llava:7b\"}'"

networks:
  default:
    driver: bridge