
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:delegated
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - PYTHONUNBUFFERED=1
    depends_on:
      ollama-init:
        condition: service_completed_successfully
    entrypoint: >
      sh -c "
        echo 'Waiting for Ollama...';
        until curl -s ollama:11434; do
          sleep 5;
        done;
        exec /app/venv/bin/python server.py
      "
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_network

  ollama-init:
    image: ollama/ollama:latest
    command: >
      sh -c "
        ollama pull llava &&
        exit 0
      "
    volumes:
      - ollama_data:/root/.ollama
    depends_on:
      - ollama
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  ollama_data:
