name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and Start Services
        run: |
          # Pull required images first
          docker pull ollama/ollama:latest
          
          # Start ollama service first
          docker compose up -d ollama
          
          # Wait for ollama to be healthy
          echo "Waiting for Ollama to be ready..."
          attempt=1
          max_attempts=30
          until docker compose ps ollama | grep -q "healthy" || [ $attempt -gt $max_attempts ]; do
            echo "Attempt $attempt/$max_attempts: Waiting for Ollama to be healthy..."
            docker compose logs ollama
            sleep 10
            attempt=$((attempt + 1))
          done
          
          if [ $attempt -gt $max_attempts ]; then
            echo "Ollama failed to become healthy after $max_attempts attempts"
            exit 1
          fi
          
          # Start remaining services
          docker compose up -d
      
      - name: Display Service Status
        if: always()
        run: |
          echo "=== Container Status ==="
          docker compose ps
          
          echo "=== Ollama Logs ==="
          docker compose logs ollama
          
          echo "=== Backend Logs ==="
          docker compose logs backend
          
          echo "=== Resource Usage ==="
          docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}\t{{.BlockIO}}"
