name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Increased timeout for better handling
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and Push Docker Images
        run: |
          # Build images with detailed output
          docker compose build --progress=plain
          
          # Start services
          docker compose up -d
          
          # Wait and check service health
          echo "Waiting for services to initialize..."
          for i in {1..12}; do
            echo "Check $i of 12..."
            if docker compose ps | grep -q "running"; then
              echo "Services are running"
              break
            fi
            sleep 10
          done
      
      - name: Display Service Logs
        if: always()
        run: |
          echo "=== Full Docker Compose Logs ==="
          docker compose logs
          
          echo "=== Backend Build and Runtime Logs ==="
          docker compose logs backend
          
          echo "=== Python Package Installation Logs ==="
          docker compose exec backend pip freeze || true
          
          echo "=== Container Status ==="
          docker compose ps
          
          echo "=== Disk Space Information ==="
          df -h
