name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose up -d

      - name: Check Running Containers
        run: docker ps -a

      - name: Show Backend Logs (If Crashes)
        run: docker logs $(docker ps -aqf "name=backend") || true
