name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and Start Services
        run: |
          # Pull required images first
          docker pull ollama/ollama:latest
          
          # Build images
          docker compose build --no-cache --progress=plain
          
          # Start services
          docker compose up -d
          
          # Wait for services to initialize
          echo "Waiting for services to initialize..."
          sleep 30
      
      - name: Check Ollama Status
        run: |
          echo "Checking Ollama service status..."
          docker compose logs ollama
          
          echo "Checking Ollama initialization status..."
          docker compose logs ollama-init
      
      - name: Check Backend Status
        run: |
          echo "Checking Backend service status..."
          docker compose logs backend
      
      - name: Display All Services Status
        if: always()
        run: |
          echo "=== Container Status ==="
          docker compose ps
          
          echo "=== Full Service Logs ==="
          docker compose logs
          
          echo "=== Resource Usage ==="
          docker stats --no-stream
